---

# ANSIBLE 2 ISSUE: Need to specify the handlers fully, because
# otherwise whatever variable is used always has the first
# value it was ever bound to, not the one the role currently
# uses.

- name: Reload haproxy demo-haproxy
  ansible.builtin.service:
    name: "demo-haproxy"
    state: reloaded
  when: _haproxy.reload_if_changed and (configuration is changed or certificates is changed or error_files is changed)

- name: Restart rsyslog
  ansible.builtin.service:
    name: "rsyslog"
    state: restarted
  when: _haproxy.reload_if_changed and rsyslog is changed
