---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Fake Debian 12 due to python3-apt being from trixie
      ansible.builtin.set_fact:
        ansible_distribution_major_version: 12
        ansible_distribution_release: "bookworm"

    - name: update APT Cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      register: result
      until: result is succeeded
      when: ansible_os_family == 'Debian'

    # skip idempotence tests
    - name: Include HAProxy install role
      ansible.builtin.include_role:
        name: haproxy
      when: "'molecule-idempotence-notest' not in ansible_skip_tags"

  tasks:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
